dataFileName: data/persistentData.tsv
logFileName: data/transactionLog.tsv

logging:
  level: INFO

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
